apiVersion: v1
kind: Secret
metadata:
  name: sierra-sync-secrets
  namespace: sierra-sync
  labels:
    app: sierra-sync-platform
    component: secrets
type: Opaque
stringData:
  # Database Credentials (these would be base64 encoded in real deployment)
  DATABASE_USERNAME: "sierra_sync_user"
  DATABASE_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  DATABASE_URL: "postgresql://sierra_sync_user:CHANGE_ME_IN_PRODUCTION@sierra-sync-postgres-primary:5432/sierra_sync"
  
  # Redis Credentials
  REDIS_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  REDIS_URL: "redis://:CHANGE_ME_IN_PRODUCTION@sierra-sync-redis-master:6379/0"
  
  # JWT Secrets
  JWT_SECRET: "CHANGE_ME_IN_PRODUCTION_MIN_256_BITS"
  JWT_REFRESH_SECRET: "CHANGE_ME_IN_PRODUCTION_MIN_256_BITS"
  
  # Encryption Keys
  FIELD_ENCRYPTION_KEY: "CHANGE_ME_IN_PRODUCTION_64_BYTES"
  PII_ENCRYPTION_KEY: "CHANGE_ME_IN_PRODUCTION_64_BYTES"
  FINANCIAL_ENCRYPTION_KEY: "CHANGE_ME_IN_PRODUCTION_64_BYTES"
  
  # Third-party API Keys
  SENTRY_DSN: "https://your-sentry-dsn@sentry.io/project-id"
  STRIPE_SECRET_KEY: "sk_live_CHANGE_ME_IN_PRODUCTION"
  STRIPE_WEBHOOK_SECRET: "whsec_CHANGE_ME_IN_PRODUCTION"
  SENDGRID_API_KEY: "SG.CHANGE_ME_IN_PRODUCTION"
  
  # CRM Integration Keys
  HUBSPOT_CLIENT_ID: "CHANGE_ME_IN_PRODUCTION"
  HUBSPOT_CLIENT_SECRET: "CHANGE_ME_IN_PRODUCTION"
  SALESFORCE_CLIENT_ID: "CHANGE_ME_IN_PRODUCTION"
  SALESFORCE_CLIENT_SECRET: "CHANGE_ME_IN_PRODUCTION"
  ZOHO_CLIENT_ID: "CHANGE_ME_IN_PRODUCTION"
  ZOHO_CLIENT_SECRET: "CHANGE_ME_IN_PRODUCTION"
  
  # OAuth2 Secrets
  OAUTH2_CLIENT_SECRET: "CHANGE_ME_IN_PRODUCTION"
  OAUTH2_SIGNING_KEY: "CHANGE_ME_IN_PRODUCTION"

---
apiVersion: v1
kind: Secret
metadata:
  name: sierra-sync-tls
  namespace: sierra-sync
  labels:
    app: sierra-sync-platform
    component: tls
type: kubernetes.io/tls
data:
  # These would be actual certificate files in production
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...  # base64 encoded certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...  # base64 encoded private key

---
apiVersion: v1
kind: Secret
metadata:
  name: sierra-sync-registry
  namespace: sierra-sync
  labels:
    app: sierra-sync-platform
    component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZ2l0aHViX3VzZXJuYW1lIiwicGFzc3dvcmQiOiJnaXRodWJfcGF0IiwiYXV0aCI6IloybDBhSFZpWDNWelpYSnVZVzFsT21kcGRHaDFZbDl3WVhRPSJ9fX0=

---
# External Secrets Operator Configuration (for AWS Secrets Manager integration)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: sierra-sync
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyID:
            name: aws-credentials
            key: access-key-id
          secretAccessKey:
            name: aws-credentials
            key: secret-access-key

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sierra-sync-external-secrets
  namespace: sierra-sync
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: sierra-sync-external-secrets
    creationPolicy: Owner
  data:
    - secretKey: database-credentials
      remoteRef:
        key: sierra-sync/prod/database-primary
        property: password
    - secretKey: jwt-keys
      remoteRef:
        key: sierra-sync/prod/jwt-keys
        property: access_secret
    - secretKey: field-encryption-keys
      remoteRef:
        key: sierra-sync/prod/field-encryption
        property: master_key