# Secret Management Initialization Configuration
# Sierra Sync Platform - Secrets Bootstrap

version: "1.0"
description: "Initial secrets configuration for Sierra Sync platform"

# Environment-specific secret configurations
environments:
  development:
    provider: "vault"  # Use Vault for development
    vault:
      url: "http://localhost:8200"
      engine_path: "secret"
      namespace: "sierra-sync-dev"
    
    secrets:
      - name: "database/credentials"
        value:
          host: "localhost"
          port: 5432
          database: "sierra_sync_dev"
          username: "postgres"
          password: "{{ GENERATE_PASSWORD }}"
        metadata:
          description: "Development database credentials"
          rotation_enabled: false
          
      - name: "jwt/signing-keys"
        value:
          access_secret: "{{ GENERATE_SECRET_64 }}"
          refresh_secret: "{{ GENERATE_SECRET_64 }}"
        metadata:
          description: "JWT signing keys for development"
          rotation_enabled: false
          
      - name: "redis/credentials"
        value:
          url: "redis://localhost:6379"
          password: "{{ GENERATE_PASSWORD }}"
        metadata:
          description: "Redis connection credentials"
          
      - name: "crm/api-keys"
        value:
          hubspot:
            client_id: "{{ PLACEHOLDER }}"
            client_secret: "{{ PLACEHOLDER }}"
          salesforce:
            client_id: "{{ PLACEHOLDER }}"
            client_secret: "{{ PLACEHOLDER }}"
          zoho:
            client_id: "{{ PLACEHOLDER }}"
            client_secret: "{{ PLACEHOLDER }}"
        metadata:
          description: "CRM API keys and secrets"
          rotation_enabled: true
          rotation_schedule: "quarterly"

  staging:
    provider: "aws"  # Use AWS Secrets Manager for staging
    aws:
      region: "us-east-1"
      
    secrets:
      - name: "sierra-sync/staging/database"
        value:
          host: "{{ RDS_ENDPOINT }}"
          port: 5432
          database: "sierra_sync_staging"
          username: "sierra_sync_user"
          password: "{{ GENERATE_PASSWORD_32 }}"
        metadata:
          description: "Staging database credentials"
          rotation_enabled: true
          rotation_schedule: "monthly"
          tags:
            Environment: "staging"
            Application: "sierra-sync"
            Component: "database"
            
      - name: "sierra-sync/staging/jwt-keys"
        value:
          access_secret: "{{ GENERATE_SECRET_64 }}"
          refresh_secret: "{{ GENERATE_SECRET_64 }}"
        metadata:
          description: "JWT signing keys for staging"
          rotation_enabled: true
          rotation_schedule: "quarterly"
          tags:
            Environment: "staging"
            Application: "sierra-sync"
            Component: "auth"
            
      - name: "sierra-sync/staging/redis"
        value:
          url: "{{ ELASTICACHE_ENDPOINT }}"
          password: "{{ GENERATE_PASSWORD_32 }}"
        metadata:
          description: "Redis credentials for staging"
          rotation_enabled: true
          rotation_schedule: "monthly"
          
      - name: "sierra-sync/staging/encryption-keys"
        value:
          field_encryption_key: "{{ GENERATE_SECRET_64 }}"
          file_encryption_key: "{{ GENERATE_SECRET_64 }}"
        metadata:
          description: "Field-level encryption keys"
          rotation_enabled: true
          rotation_schedule: "yearly"
          
      - name: "sierra-sync/staging/crm-integrations"
        value:
          hubspot:
            client_id: "{{ HUBSPOT_CLIENT_ID }}"
            client_secret: "{{ HUBSPOT_CLIENT_SECRET }}"
            webhook_secret: "{{ GENERATE_SECRET_32 }}"
          salesforce:
            client_id: "{{ SALESFORCE_CLIENT_ID }}"
            client_secret: "{{ SALESFORCE_CLIENT_SECRET }}"
            webhook_secret: "{{ GENERATE_SECRET_32 }}"
          zoho:
            client_id: "{{ ZOHO_CLIENT_ID }}"
            client_secret: "{{ ZOHO_CLIENT_SECRET }}"
            webhook_secret: "{{ GENERATE_SECRET_32 }}"
        metadata:
          description: "CRM integration credentials"
          rotation_enabled: true
          rotation_schedule: "quarterly"
          
      - name: "sierra-sync/staging/third-party-apis"
        value:
          sentry_dsn: "{{ SENTRY_DSN }}"
          stripe_secret_key: "{{ STRIPE_SECRET_KEY }}"
          stripe_webhook_secret: "{{ STRIPE_WEBHOOK_SECRET }}"
          sendgrid_api_key: "{{ SENDGRID_API_KEY }}"
        metadata:
          description: "Third-party API credentials"
          rotation_enabled: false
          
      - name: "sierra-sync/staging/oauth2-clients"
        value:
          web_app:
            client_id: "{{ GENERATE_CLIENT_ID }}"
            client_secret: "{{ GENERATE_SECRET_32 }}"
          mobile_app:
            client_id: "{{ GENERATE_CLIENT_ID }}"
            # No client secret for public clients
          api_client:
            client_id: "{{ GENERATE_CLIENT_ID }}"
            client_secret: "{{ GENERATE_SECRET_32 }}"
        metadata:
          description: "OAuth2 client credentials"
          rotation_enabled: true
          rotation_schedule: "yearly"

  production:
    provider: "aws"  # Use AWS Secrets Manager for production
    aws:
      region: "us-east-1"
      kms_key_id: "{{ KMS_KEY_ARN }}"  # Use KMS for encryption
      
    secrets:
      - name: "sierra-sync/prod/database-primary"
        value:
          host: "{{ RDS_PRIMARY_ENDPOINT }}"
          port: 5432
          database: "sierra_sync"
          username: "sierra_sync_user"
          password: "{{ GENERATE_PASSWORD_64 }}"
        metadata:
          description: "Production primary database credentials"
          rotation_enabled: true
          rotation_schedule: "monthly"
          tags:
            Environment: "production"
            Application: "sierra-sync"
            Component: "database"
            Tier: "primary"
            
      - name: "sierra-sync/prod/database-replica"
        value:
          host: "{{ RDS_REPLICA_ENDPOINT }}"
          port: 5432
          database: "sierra_sync"
          username: "sierra_sync_readonly"
          password: "{{ GENERATE_PASSWORD_64 }}"
        metadata:
          description: "Production read replica database credentials"
          rotation_enabled: true
          rotation_schedule: "monthly"
          
      - name: "sierra-sync/prod/jwt-keys"
        value:
          access_secret: "{{ GENERATE_SECRET_64 }}"
          refresh_secret: "{{ GENERATE_SECRET_64 }}"
          algorithm: "RS256"
          private_key: "{{ GENERATE_RSA_PRIVATE_KEY }}"
          public_key: "{{ GENERATE_RSA_PUBLIC_KEY }}"
        metadata:
          description: "JWT signing keys for production"
          rotation_enabled: true
          rotation_schedule: "quarterly"
          
      - name: "sierra-sync/prod/redis-cluster"
        value:
          primary_endpoint: "{{ REDIS_PRIMARY_ENDPOINT }}"
          replica_endpoint: "{{ REDIS_REPLICA_ENDPOINT }}"
          auth_token: "{{ GENERATE_PASSWORD_64 }}"
        metadata:
          description: "Redis cluster credentials"
          rotation_enabled: true
          rotation_schedule: "monthly"
          
      - name: "sierra-sync/prod/field-encryption"
        value:
          master_key: "{{ GENERATE_SECRET_64 }}"
          pii_encryption_key: "{{ GENERATE_SECRET_64 }}"
          financial_encryption_key: "{{ GENERATE_SECRET_64 }}"
        metadata:
          description: "Field-level encryption keys"
          rotation_enabled: true
          rotation_schedule: "yearly"
          
      - name: "sierra-sync/prod/api-keys"
        value:
          internal_api_key: "{{ GENERATE_API_KEY }}"
          webhook_signing_key: "{{ GENERATE_SECRET_64 }}"
          rate_limit_key: "{{ GENERATE_SECRET_32 }}"
        metadata:
          description: "Internal API keys"
          rotation_enabled: true
          rotation_schedule: "quarterly"

# Secret generation templates
generators:
  GENERATE_PASSWORD: "password:32:alphanumeric"
  GENERATE_PASSWORD_32: "password:32:complex"
  GENERATE_PASSWORD_64: "password:64:complex"
  GENERATE_SECRET_32: "secret:32:base64url"
  GENERATE_SECRET_64: "secret:64:base64url"
  GENERATE_CLIENT_ID: "client_id:16:hex"
  GENERATE_API_KEY: "api_key:32:base64url:sk_"
  GENERATE_RSA_PRIVATE_KEY: "rsa:2048:private"
  GENERATE_RSA_PUBLIC_KEY: "rsa:2048:public"

# Placeholder mappings for environment variables
placeholders:
  RDS_ENDPOINT: "${RDS_ENDPOINT}"
  RDS_PRIMARY_ENDPOINT: "${RDS_PRIMARY_ENDPOINT}"
  RDS_REPLICA_ENDPOINT: "${RDS_REPLICA_ENDPOINT}"
  ELASTICACHE_ENDPOINT: "${ELASTICACHE_ENDPOINT}"
  REDIS_PRIMARY_ENDPOINT: "${REDIS_PRIMARY_ENDPOINT}"
  REDIS_REPLICA_ENDPOINT: "${REDIS_REPLICA_ENDPOINT}"
  KMS_KEY_ARN: "${KMS_KEY_ARN}"
  HUBSPOT_CLIENT_ID: "${HUBSPOT_CLIENT_ID}"
  HUBSPOT_CLIENT_SECRET: "${HUBSPOT_CLIENT_SECRET}"
  SALESFORCE_CLIENT_ID: "${SALESFORCE_CLIENT_ID}"
  SALESFORCE_CLIENT_SECRET: "${SALESFORCE_CLIENT_SECRET}"
  ZOHO_CLIENT_ID: "${ZOHO_CLIENT_ID}"
  ZOHO_CLIENT_SECRET: "${ZOHO_CLIENT_SECRET}"
  SENTRY_DSN: "${SENTRY_DSN}"
  STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}"
  STRIPE_WEBHOOK_SECRET: "${STRIPE_WEBHOOK_SECRET}"
  SENDGRID_API_KEY: "${SENDGRID_API_KEY}"

# Rotation policies
rotation_policies:
  weekly:
    schedule: "0 2 * * 1"  # Every Monday at 2 AM
    grace_period_days: 1
    
  monthly:
    schedule: "0 3 1 * *"  # First day of month at 3 AM
    grace_period_days: 7
    
  quarterly:
    schedule: "0 4 1 */3 *"  # First day of quarter at 4 AM
    grace_period_days: 30
    
  yearly:
    schedule: "0 5 1 1 *"  # January 1st at 5 AM
    grace_period_days: 90

# Security policies
security_policies:
  encryption_at_rest: true
  encryption_in_transit: true
  access_logging: true
  audit_trail: true
  
  # Password policies
  password_policy:
    min_length: 32
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_symbols: true
    exclude_ambiguous: true
    
  # Secret policies  
  secret_policy:
    min_length: 32
    format: "base64url"
    entropy_bits: 256
    
  # Access policies
  access_policy:
    require_mfa: true
    session_timeout: 3600  # 1 hour
    max_failed_attempts: 3
    lockout_duration: 300  # 5 minutes

# Monitoring and alerting
monitoring:
  secret_access_logging: true
  rotation_alerts: true
  expiration_warnings: true
  
  alert_thresholds:
    expiration_warning_days: 30
    rotation_failure_retries: 3
    access_anomaly_threshold: 10
    
  notification_channels:
    slack_webhook: "${SLACK_WEBHOOK_URL}"
    pagerduty_key: "${PAGERDUTY_KEY}"
    email_recipients:
      - "security@sierrasync.com"
      - "devops@sierrasync.com"

# Backup and recovery
backup:
  enabled: true
  frequency: "daily"
  retention_days: 90
  cross_region_backup: true
  encryption: true
  
recovery:
  rpo_minutes: 5   # Recovery Point Objective
  rto_minutes: 30  # Recovery Time Objective
  
# Compliance settings
compliance:
  pci_dss: true
  soc2: true
  gdpr: true
  hipaa: false  # Not handling health data
  
  data_classification:
    secret: "restricted"
    api_key: "confidential"
    password: "restricted"
    certificate: "confidential"